name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - run: yarn run lint

      - run: yarn run tsc

      - run: yarn run test